USE [PTR]
GO

/****** Object:  Table [dbo].[Failure]    Script Date: 07/02/2014 09:25:29 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[Failure](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Fail] [varchar](50) NULL,
	[FailGroup] [int] NULL,
 CONSTRAINT [PK_Failure] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[Failure]  WITH CHECK ADD  CONSTRAINT [FK_Failure_FailGroup] FOREIGN KEY([FailGroup])
REFERENCES [dbo].[FailGroup] ([Id])
GO

ALTER TABLE [dbo].[Failure] CHECK CONSTRAINT [FK_Failure_FailGroup]
GO

